apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ant-exceptions-log
  labels:
      app: ant
      version: v1
spec:
  schedule: "59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ant-exceptions-log
            image: "docker-registry:8080/ant-exceptions-log:latest"
            imagePullPolicy: Always
            command: ["./flower"]
            args: ["-fmt", "text", "-interval", "24", "-email"]
            env:
            - name: flowerApi
              valueFrom:
                configMapKeyRef:
                  name: ant-exceptions-config-map
                  key: API
            - name: flowerReceivers
              valueFrom:
                configMapKeyRef:
                  name: ant-exceptions-config-map
                  key: RECEIVERS
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ant-exceptions-config-map
data:
  API: |
    http://ant-emea:5555
  RECEIVERS: |
    denys.aleksandrov@imc.com    # comma separated list of emails
