apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ant-exceptions-log
  labels:
      app: ant
      version: v1
spec:
  schedule: "59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ant-exceptions-log
            image: "docker-registry:8080/ant-exceptions-log:latest"
            imagePullPolicy: Always
            command: ["./flower"]
            args: ["-fmt", "text", "-interval", "24", "-email"]
            envFrom:
            - configMapRef:
                name: ant-exceptions-config-map
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ant-exceptions-config-map
data:
  flowerApi: |-
    http://ant-emea.trading.imc.intra:5555/api/tasks
  flowerReceivers: |-
    denys.aleksandrov@imc.com
